# Generated by Django 3.0.7 on 2020-07-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorApplicationRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='Tutor', max_length=30)),
                ('lastname', models.CharField(default='Tutor', max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=200)),
            ],
        ),
    ]
