# Generated by Django 3.0.7 on 2020-07-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('TutorID', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='Tutor', max_length=30)),
                ('lastname', models.CharField(default='Tutor', max_length=30)),
                ('bio', models.CharField(max_length=500)),
            ],
        ),
    ]
