# Generated by Django 3.0.7 on 2020-07-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Edu-sprint town', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Edu-land', max_length=30),
        ),
    ]
