# Generated by Django 3.0.7 on 2020-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_platform', '0002_auto_20200709_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
